---
version: "3.7"

services:
  # api-gateway:
  #   build: ./api-gateway
  #   env_file: .env
  #   ports:
  #     - "8090:8080"
  #   links:
  #     - customers-api
  #     - events-api

  customers-api:
    build: ./customers-api
    env_file: .env
    ports: 
      - 8091:80
    expose: 
      - 8091
  events-api:
    build: ./events-api
    env_file: .env
    ports: 
      - 8092:8000
    expose:
      - 8092
